baseURL = 'https://danfreimann.dev/'
languageCode = 'en-us'
title = 'danfreimann.dev'
theme = "paper"
publishDir = "docs"

[params]
  # Header for social icons
	rss = true
	github = 'github.com/Melriax'
